<?php
    //Although this video feature is in the form of a PHP function, we're keeping it separate from the theme's library directory and moving it into it's own global widgets folder to keep more consistency with the M&R Master Theme's modular structure. 

    //If you do need to make adjustments, it will likely be in the HTML generated by the function below, or the CSS rules from the file in this widget's folder. _video-player.scss
    
    //I found that as I was building more complexity into the shortcode, I needed to use a regular function for the various modules instead:
    function mandr_video_player(
        $video_link = '', 
        $poster_image_array = [], 
        $video_description = '', 
        $video_aria_id = ''
    ) {

        if (empty($video_description)) {
            $video_description = 'play video';
        }

        //accessibility practice - include an HTML indicator for the description of the video 
        //it doesn't directly connect to the <video> tag itself from the vendor script, but we tried
        if (empty($video_aria_id)) {
            $aria_describedby_string = '';
            $aria_id_string = '';
        } else {
            $aria_describedby_string = 'aria-describedby="'.$video_aria_id.'"';
            $aria_id_string = 'id="'.$video_aria_id.'"';
        }
        
        
        if ($video_link) {
            //using the link string, we'll need to determine which platform the video is hosted on & take the appropriate actions:
            if (str_contains($video_link, 'youtube')) { 
                //extract the video 
                $youtube_id = youtube_video_id($video_link);

                if (empty($poster_image_array)) {
                    $image_url = 'https://img.youtube.com/vi/' . $youtube_id . '/0.jpg';
                    $image_width = 480;
                    $image_height = 360;
                    $image_alt = 'default video thumbnail image supplied by YouTube';
                } else {
                    $image_url = $poster_image_array['poster_image_url'];
                    $image_width = $poster_image_array['poster_image_width'];
                    $image_height = $poster_image_array['poster_image_height'];
                    $image_alt = $poster_image_array['poster_image_alt'];
                }

                $output = '
                <a href="https://www.youtube.com/watch?v=' . $youtube_id . '" class="popup-video" '.$aria_describedby_string.'>
                    <img class="poster-image" src="' . $image_url . '" width="' . $image_width . '" height="' . $image_height . '" alt="'.$image_alt.'">
                    <span class="play-icon" '.$aria_id_string.'>'.$video_description.'</span>
                </a>
                ';

                return $output;

            } elseif (str_contains($video_link, 'vimeo')) {                

                if (empty($poster_image_array)) {
                    //Load in the oEmbed XML
                    $oembed_endpoint = 'http://vimeo.com/api/oembed';
                    $xml_url = $oembed_endpoint . '.xml?url=' . rawurlencode($video_link) . '&width=640&byline=false&title=false';
                    $oembed = simplexml_load_string(curl_get($xml_url)); 

                    //grab the image url:
                    $image_url = html_entity_decode($oembed->thumbnail_url);

                    $image_width = 640;
                    $image_height = 360;
                    $image_alt = 'default video thumbnail image supplied by Vimeo';
                } else {
                    $image_url = $poster_image_array['poster_image_url'];
                    $image_width = $poster_image_array['poster_image_width'];
                    $image_height = $poster_image_array['poster_image_height'];
                    $image_alt = $poster_image_array['poster_image_alt'];
                }

                $output = '
                <a href="' . $video_link . '" class="popup-video" '.$aria_describedby_string.'>
                    <img class="poster-image" src="' . $image_url . '" width="' . $image_width . '" height="' . $image_height . '" alt="'.$image_alt.'">
                    <span class="play-icon" '.$aria_id_string.'>'.$video_description.'</span>
                </a>
                ';

                return $output;

            }  else {
                echo '<h2>Video link format is not supported</h2>';
                return;
            } 
        } 
        
        return;
    }

    //Take any standard youtube link and return the video ID
    function youtube_video_id($url) {
        // Youtube Video id is 11 characters in length
        $video_pattern = '~(?:http|https|)(?::\/\/|)(?:www.|)(?:youtu\.be\/|youtube\.com(?:\/embed\/|\/v\/|\/watch\?v=|\/ytscreeningroom\?v=|\/feeds\/api\/videos\/|\/user\S*[^\w\-\s]|\S*[^\w\-\s]))([\w\-]{11})[a-z0-9;:@#?&%=+\/\$_.-]*~i';

        return preg_replace($video_pattern, '$1', $url);
    }
?>