<?php
    //grab the arguments passed to this template file:
    $media_type = $args['media_type'];
    $slide_count = $args['slide_count'];
    $slide_image = $args['slide_image'];
    $slide_video = $args['slide_video'];
    $modal_ID = $args['modal_ID'];
    $slider_ID = $args['slider_ID'];

    //if the slide is an image only:
    if ($media_type == 'image') { 
        //grab the URL, width, height, & alt:       
        $slide_image_url = $slide_image['url'];
        $slide_image_width = $slide_image['width'];
        $slide_image_height = $slide_image['height'];
        $slide_image_alt = $slide_image['alt'];
    } else {
    //the slide is a video:
        $video_link = $slide_video['video_link'];
        $poster_image = $slide_video['poster_image']; 
         
        if (str_contains($video_link, 'youtube')) { 
            //extract the video 
            $youtube_id = youtube_video_id($video_link);            

            if ($poster_image) {
                $slide_image_url = $poster_image['url'];
                $slide_image_width = $poster_image['width'];
                $slide_image_height = $poster_image['height'];
                $slide_image_alt = $poster_image['alt'];
            } else {
                $slide_image_url = 'https://img.youtube.com/vi/' . $youtube_id . '/0.jpg';
                $slide_image_width = '480';
                $slide_image_height = '360';
                $slide_image_alt = 'video thumbnail generated by YouTube';
            }             
        } elseif (str_contains($video_link, 'vimeo')) {                

            if ($poster_image) {
                $slide_image_url = $poster_image['url'];
                $slide_image_width = $poster_image['width'];
                $slide_image_height = $poster_image['height'];
                $slide_image_alt = $poster_image['alt'];
            } else {
                //Load in the oEmbed XML
                $oembed_endpoint = 'http://vimeo.com/api/oembed';
                $xml_url = $oembed_endpoint . '.xml?url=' . rawurlencode($video_link) . '&width=640&byline=false&title=false';
                $oembed = simplexml_load_string(curl_get($xml_url)); 

                //grab the image url:
                $slide_image_url = html_entity_decode($oembed->thumbnail_url);

                $slide_image_width = '640';
                $slide_image_height = '360';
                $slide_image_alt = 'video thumbnail generated by Vimeo';
            } 
        }
    }
?>
<button 
    class="masonry-slide-thumbnail"
    style="background-image: url('<?= $slide_image_url ?>')"
    data-media-type="<?= $media_type ?>" 
    data-modal-ID="<?= $modal_ID ?>"
    data-slider-ID="<?= $slider_ID ?>"
    data-slide-count="<?= $slide_count ?>"
>
    <img 
        src="<?= $slide_image_url ?>"
        width="<?= $slide_image_width ?>"
        height="<?= $slide_image_height ?>"
        alt="<?= $slide_image_alt ?>"
    >
    <?php
        if ($media_type == 'video') :
    ?>
        <span class="play-icon">
    <?php
        endif;
    ?>
    <span class="screenreader-only">navigation button for the media gallery slider</span>
    <?php
        if ($media_type == 'video') :
    ?>  
        </span>
    <?php
        endif;
    ?>
</button>
<?php
    //on mobile, we don't want to use the 

    if ($media_type == 'video') {
        if ($slide_video['poster_image']) {
            echo mandr_video_player(
                $slide_video['video_link'], 
                [
                    'poster_image_url' => $slide_video['poster_image']['url'],
                    'poster_image_width' => $slide_video['poster_image']['width'],
                    'poster_image_height' => $slide_video['poster_image']['height'],
                    'poster_image_alt' => $slide_video['poster_image']['alt']
                ], 
                $slide_video['video_description'], 
                rand(0, 999)
            );
        } else {
            echo mandr_video_player(
                $slide_video['video_link'], 
                [], 
                $slide_video['video_description'], 
                rand(0, 999)
            );
        }       
    }
?>